    if (c % 2 === 0)
        console.log(c);
});

//using filter keyword
console.log("\nusing filter...");
let evenArr = num.filter(x => x % 2 === 0);
// filter will return true or false
console.log(evenArr);
console.log(evenArr[1]);

// printing using forEach for the array generated by the filter
console.log("\nprinting odd ones using forEach...");
num.filter(y => y %2 === 1)
    .forEach( z => {
        console.log(z);
    })

// map , "this is what i am looking for!!!!!!"

//*******it modifies the value in an array

let k = 1;